''' From wowwiki.  Update before re-scanning spells/items. '''

GCD_ITEMS = {
}

NO_GCD_SPELLS = {
    'Arcane Power': False,
    'Avenging Wrath': False,
    'Berserking': False,
    'Blood Fury': False,
    'Charge': False,
    'Charge(Rank 1)': False,
    'Charge(Rank 2)': False,
    'Charge(Rank 3)': False,
    'Charge(Rank 4)': False,
    'Charge(Rank 5)': False,
    'Charge(Rank 6)': False,
    'Chastise': False,
    'Cleave': False,
    'Cleave(Rank 1)': False,
    'Cleave(Rank 2)': False,
    'Cleave(Rank 3)': False,
    'Cleave(Rank 4)': False,
    'Cleave(Rank 5)': False,
    'Cleave(Rank 6)': False,
    'Cleave(Rank 7)': False,
    'Cleave(Rank 8)': False,
    'Cold Blood': False,
    'Cold Snap': False,
    'Combustion': False,
    'Counterspell': False,
    'Deterrence': False,
    'Divine Favor': False,
    'Elemental Mastery': False,
    'Evasion': False,
    'Evasion(Rank 1)': False,
    'Evasion(Rank 2)': False,
    'Fel Domination': False,
    'Hammer of Wrath': False,
    'Hammer of Wrath(Rank 1)': False,
    'Hammer of Wrath(Rank 2)': False,
    'Hammer of Wrath(Rank 3)': False,
    'Hammer of Wrath(Rank 4)': False,
    'Hammer of Wrath(Rank 5)': False,
    'Hammer of Wrath(Rank 6)': False,
    'Heroic Strike': False,
    'Heroic Strike(Rank 1)': False,
    'Heroic Strike(Rank 10)': False,
    'Heroic Strike(Rank 11)': False,
    'Heroic Strike(Rank 12)': False,
    'Heroic Strike(Rank 13)': False,
    'Heroic Strike(Rank 2)': False,
    'Heroic Strike(Rank 3)': False,
    'Heroic Strike(Rank 4)': False,
    'Heroic Strike(Rank 5)': False,
    'Heroic Strike(Rank 6)': False,
    'Heroic Strike(Rank 7)': False,
    'Heroic Strike(Rank 8)': False,
    'Heroic Strike(Rank 9)': False,
    'Inner Focus': False,
    'Intercept': False,
    'Intercept(Rank 1)': False,
    'Intercept(Rank 2)': False,
    'Intercept(Rank 3)': False,
    'Intercept(Rank 4)': False,
    'Intercept(Rank 5)': False,
    'Judgement of Blood': False,
    'Judgement of Blood(Rank 1)': False,
    'Judgement of Command': False,
    'Judgement of Command(Rank 1)': False,
    'Judgement of Corruption': False,
    'Judgement of Corruption(Rank 1)': False,
    'Judgement of Darkness': False,
    'Judgement of Justice': False,
    'Judgement of Light': False,
    'Judgement of Light(Rank 1)': False,
    'Judgement of Reckoning': False,
    'Judgement of Righteousness': False,
    'Judgement of Righteousness(Rank 1)': False,
    'Judgement of Vengeance': False,
    'Judgement of Vengeance(Rank 1)': False,
    'Judgement of Wisdom': False,
    'Judgement of Wisdom(Rank 1)': False,
    'Judgement of the Flame': False,
    'Judgement of the Martyr': False,
    'Judgement of the Martyr(Rank 1)': False,
    'Judgement': False,
    'Kill Command': False,
    'Kill Command(Rank 1)': False,
    'Maul': False,
    'Maul(Rank 1)': False,
    'Maul(Rank 10)': False,
    'Maul(Rank 2)': False,
    'Maul(Rank 3)': False,
    'Maul(Rank 4)': False,
    'Maul(Rank 5)': False,
    'Maul(Rank 6)': False,
    'Maul(Rank 7)': False,
    'Maul(Rank 8)': False,
    'Maul(Rank 9)': False,
    'Nature\'s Swiftness': False,
    'Preparation': False,
    'Presence of Mind': False,
    'Readiness': False,
    'Rune Strike': False,
    'Rune Strike(Rank 1)': False,
    'Shadowfury': False,
    'Shadowfury(Rank 1)': False,
    'Shadowfury(Rank 2)': False,
    'Shadowfury(Rank 3)': False,
    'Shadowfury(Rank 4)': False,
    'Shadowfury(Rank 5)': False,
    'Shield Bash': False,
    'Shield Bash(Rank 4)': False,
    'Shield Block': False,
    'Sprint': False,
    'Sprint(Rank 1)': False,
    'Sprint(Rank 2)': False,
    'Sprint(Rank 3)': False,
    'Sweeping Strikes': False,
    'Sweeping Strikes(Rank 1)': False,
    'Vanish': False,
    'Vanish(Rank 1)': False,
    'Vanish(Rank 2)': False,
    'Vanish(Rank 3)': False,
    'War Stomp': False,
    }
